cmake_minimum_required(VERSION 3.8)
project(rover_control)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(geometry_msgs REQUIRED)
add_executable(rover_control_node src/rover_control_node.cpp)
ament_target_dependencies(rover_control_node rclcpp geometry_msgs)
install(TARGETS rover_control_node DESTINATION lib/${PROJECT_NAME})
ament_package()
